# Generated by Django 2.1 on 2020-01-04 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('describe', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.Seller')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterIndexTogether(
            name='types',
            index_together={('id', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together={('id', 'name')},
        ),
        migrations.AddField(
            model_name='goods',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.Tag'),
        ),
        migrations.AddField(
            model_name='goods',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.Types'),
        ),
        migrations.AlterIndexTogether(
            name='goods',
            index_together={('id', 'name')},
        ),
    ]
