# Generated by Django 2.1 on 2020-01-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200104_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goodsImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
