# Generated by Django 2.1 on 2020-01-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_goods_goodsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='describe',
            field=models.CharField(max_length=500),
        ),
    ]
